<h1>NUMPY BASICS</h1>
<hr style="border: none; height: 4px; background-color: #210bb3ff; width: 100%;">

<b>Lorenz V. Camoraha</b>
<p>Comptech Student T09</p>
<p>12/14/2025</p>
<hr style="border: none; height: 4px; background-color: #210bb3ff; width: 100%;">


In [14]:
#imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

In [10]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

In [11]:
np.shape(my_array)

(3,)

<h1>2D ARRAY</h1>
<hr style="border: none; height: 4px; background-color: #210bb3ff; width: 100%;">


In [15]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])

my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.shape(my_array)

(2, 3)

In [18]:
my_array = my_array.T
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
np.shape(my_array)

(3, 2)

<h1>MEASURES OF CENTRAL TENDENCY</h1>
<hr style="border: none; height: 4px; background-color: #210bb3ff; width: 100%;">

In [21]:
# Jaguar vs Panther
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [22]:
np.shape(resistance)

(2, 11)

In [23]:
res_mean = np.nanmean(resistance,axis=1)
res_mean

array([ 9.4 , 10.75])

In [24]:
print("Jaguar Mean:" + str((res_mean[0]).round(2))+" ohms")

Jaguar Mean:9.4 ohms


In [25]:
print(f'Jaguar:{res_mean[0]:.2f} ohms')
print(f'Panther:{res_mean[1]:.2f} ohms')

Jaguar:9.40 ohms
Panther:10.75 ohms


In [26]:
res_median = np.nanmedian(resistance,axis=1)
res_median

array([9.8 , 9.55])

In [27]:
print(f'Jaguar:{res_median[0]:.2f} ohms')
print(f'Panther:{res_median[1]:.2f} ohms')

Jaguar:9.80 ohms
Panther:9.55 ohms


In [28]:
res_mode = stats.mode(resistance,axis=1)
res_mode

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [29]:
jag_res = resistance[0]
print("Jaguar mode: ")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar mode: 
9.8 ohms
10.4 ohms


In [30]:
pan_res = resistance[1]
print("Panther mode: ")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther mode: 
9.1 ohms


In [31]:
# Jaguar vs Panther
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance


array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [32]:
# Range
res_max = np.nanmax(resistance,axis=1)
res_min = np.nanmin(resistance,axis=1)
res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [33]:
print(f'Jaguar range: {res_range[0]:.2f} ohms')
print(f'Panther range: {res_range[1]:.2f} ohms')

Jaguar range: 8.00 ohms
Panther range: 10.90 ohms


In [34]:
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [35]:
# IQR
res_Q3 = np.nanpercentile(resistance,75,axis=1)
res_Q3

array([10.45 , 10.625])

In [ ]:
print(f'Panther IQR: {res_Q3[0]-res_Q1[0]:.2f}ohms')
print(f'Jaguar IQR: {res_Q3[1]-res_Q1[1]:.2f}ohms')

Panther IQR: 1.05ohms
Jaguar IQR: 1.50ohms


In [39]:
# Variance
res_var = np.nanvar(resistance,ddof=1,axis=1)
print(f'Jaguar Variance :{res_var[0]:.2f} ohms')
print(f'Panther Variance :{res_var[1]:.2f} ohms')

Jaguar Variance :4.86 ohms
Panther Variance :11.08 ohms


In [40]:
# Standard Deviation
res_std = np.nanstd(resistance,ddof=1,axis=1)
print(f'Jaguar Variance :{res_std[0]:.2f} ohms')
print(f'Panther Variance :{res_std[1]:.2f} ohms')

Jaguar Variance :2.20 ohms
Panther Variance :3.33 ohms
